### ISSUE TITLE
Series Artworks in Unique Artworks

### ISSUE THREAD

**Issue by RutaBinkyte** [medialab/gender_art#13]
unique_artworks.py excludes series of artworks when creating dataset.
code in lines 37-42:
separable_artworks_groups = db.Artwork.aggregate([
    {"$match": {"type":'separable'}},
    {'$group': dict( [('_id','ensemble_id')] + [(k,{'$first':'$%s'%k}) for k,v in project.items()])},
    {"$project":project}
    ])
should create a list of unique artworks from series, but it takes only the first one individual artworks of first series. It also creates '_id': 'ensemble_id' instead of the numerical id of series.

As a result all other series of artworks are excluded from the dataset.

**Comment by paulgirard** [comment]
Oh my... yes you're right that's very wrong...
I am working on it.

**Comment by paulgirard** [comment]
fixed in https://github.com/medialab/gender_art/commit/960f720f50695677d2c44f9c320ccf1dda76a103
